<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SecaoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('secoes')->insert([
            [
                'secao' => 78,
                'local' => 'Escola João Evangelista Vasconcelos',
                'endereco' => 'Cajueirinho I',
                'bairro' => 'Zona Rural',
                'aptos' => 327,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 79,
                'local' => 'Escola João Evangelista Vasconcelos',
                'endereco' => 'Cajueirinho I',
                'bairro' => 'Zona Rural',
                'aptos' => 337,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 435,
                'local' => 'Escola João Evangelista Vasconcelos',
                'endereco' => 'Cajueirinho I',
                'bairro' => 'Zona Rural',
                'aptos' => 43,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 80,
                'local' => 'Escola Leopoldo Manoel de Medeiros',
                'endereco' => 'Preá',
                'bairro' => 'Preá',
                'aptos' => 345,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 81,
                'local' => 'Escola Leopoldo Manoel de Medeiros',
                'endereco' => 'Preá',
                'bairro' => 'Preá',
                'aptos' => 348,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 255,
                'local' => 'Escola Leopoldo Manoel de Medeiros',
                'endereco' => 'Preá',
                'bairro' => 'Preá',
                'aptos' => 345,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 286,
                'local' => 'Escola Leopoldo Manoel de Medeiros',
                'endereco' => 'Preá',
                'bairro' => 'Preá',
                'aptos' => 345,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 429,
                'local' => 'Escola Leopoldo Manoel de Medeiros',
                'endereco' => 'Preá',
                'bairro' => 'Preá',
                'aptos' => 349,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 443,
                'local' => 'Escola Leopoldo Manoel de Medeiros',
                'endereco' => 'Preá',
                'bairro' => 'Preá',
                'aptos' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 83,
                'local' => 'Escola São Francisco da Cruz',
                'endereco' => 'Rua Professora Filó, SN',
                'bairro' => 'Centro',
                'aptos' => 335,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 84,
                'local' => 'Escola São Francisco da Cruz',
                'endereco' => 'Rua Professora Filó, SN',
                'bairro' => 'Centro',
                'aptos' => 340,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 108,
                'local' => 'Escola São Francisco da Cruz',
                'endereco' => 'Rua Professora Filó, SN',
                'bairro' => 'Centro',
                'aptos' => 335,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 163,
                'local' => 'Escola São Francisco da Cruz',
                'endereco' => 'Rua Professora Filó, SN',
                'bairro' => 'Centro',
                'aptos' => 339,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 174,
                'local' => 'Escola São Francisco da Cruz',
                'endereco' => 'Rua Professora Filó, SN',
                'bairro' => 'Centro',
                'aptos' => 343,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 437,
                'local' => 'Escola São Francisco da Cruz',
                'endereco' => 'Rua Professora Filó, SN',
                'bairro' => 'Centro',
                'aptos' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 75,
                'local' => 'Escola Paulo Freire',
                'endereco' => 'Avenida 14 de Janeiro, SN',
                'bairro' => 'Aningas',
                'aptos' => 258,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 76,
                'local' => 'Escola Paulo Freire',
                'endereco' => 'Avenida 14 de Janeiro, SN',
                'bairro' => 'Aningas',
                'aptos' => 255,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 85,
                'local' => 'Escola Paulo Freire',
                'endereco' => 'Avenida 14 de Janeiro, SN',
                'bairro' => 'Aningas',
                'aptos' => 255,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 86,
                'local' => 'Escola Paulo Freire',
                'endereco' => 'Avenida 14 de Janeiro, SN',
                'bairro' => 'Aningas',
                'aptos' => 253,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 118,
                'local' => 'Escola Paulo Freire',
                'endereco' => 'Avenida 14 de Janeiro, SN',
                'bairro' => 'Aningas',
                'aptos' => 252,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 119,
                'local' => 'Escola Paulo Freire',
                'endereco' => 'Avenida 14 de Janeiro, SN',
                'bairro' => 'Aningas',
                'aptos' => 256,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 77,
                'local' => 'Escola João Ladislau de Paulo Magalhães',
                'endereco' => 'Distrito de Caiçara, SN',
                'bairro' => 'Caiçara',
                'aptos' => 292,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 89,
                'local' => 'Escola João Ladislau de Paulo Magalhães',
                'endereco' => 'Distrito de Caiçara, SN',
                'bairro' => 'Caiçara',
                'aptos' => 291,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 105,
                'local' => 'Escola João Ladislau de Paulo Magalhães',
                'endereco' => 'Distrito de Caiçara, SN',
                'bairro' => 'Caiçara',
                'aptos' => 292,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 261,
                'local' => 'Escola João Ladislau de Paulo Magalhães',
                'endereco' => 'Distrito de Caiçara, SN',
                'bairro' => 'Caiçara',
                'aptos' => 294,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 386,
                'local' => 'Escola João Ladislau de Paulo Magalhães',
                'endereco' => 'Distrito de Caiçara, SN',
                'bairro' => 'Caiçara',
                'aptos' => 291,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 90,
                'local' => 'Escola Maria Filomena Sousa',
                'endereco' => 'Cajueirinho II',
                'bairro' => 'Zona Rural',
                'aptos' => 237,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 91,
                'local' => 'Escola Maria Filomena Sousa',
                'endereco' => 'Cajueirinho II',
                'bairro' => 'Zona Rural',
                'aptos' => 239,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 388,
                'local' => 'Escola Maria Filomena Sousa',
                'endereco' => 'Cajueirinho II',
                'bairro' => 'Zona Rural',
                'aptos' => 237,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 98,
                'local' => 'Escola João Evangelista da Cruz',
                'endereco' => 'Paraguai',
                'bairro' => 'Zona Rural',
                'aptos' => 313,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 104,
                'local' => 'Escola João Evangelista da Cruz',
                'endereco' => 'Paraguai',
                'bairro' => 'Zona Rural',
                'aptos' => 311,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 254,
                'local' => 'Escola João Evangelista da Cruz',
                'endereco' => 'Paraguai',
                'bairro' => 'Zona Rural',
                'aptos' => 315,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 99,
                'local' => 'Escola Maria Pereira Brandão',
                'endereco' => 'Rua Vereador Mundico Martins, 642',
                'bairro' => 'Centro',
                'aptos' => 301,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 100,
                'local' => 'Escola Maria Pereira Brandão',
                'endereco' => 'Rua Vereador Mundico Martins, 642',
                'bairro' => 'Centro',
                'aptos' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 101,
                'local' => 'Escola Maria Pereira Brandão',
                'endereco' => 'Rua Vereador Mundico Martins, 642',
                'bairro' => 'Centro',
                'aptos' => 299,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 102,
                'local' => 'Escola Maria Pereira Brandão',
                'endereco' => 'Rua Vereador Mundico Martins, 642',
                'bairro' => 'Centro',
                'aptos' => 303,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 103,
                'local' => 'Escola Maria Pereira Brandão',
                'endereco' => 'Rua Vereador Mundico Martins, 642',
                'bairro' => 'Centro',
                'aptos' => 297,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 106,
                'local' => 'Escola Maria Pereira Brandão',
                'endereco' => 'Rua Vereador Mundico Martins, 642',
                'bairro' => 'Centro',
                'aptos' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 107,
                'local' => 'Escola Maria Pereira Brandão',
                'endereco' => 'Rua Vereador Mundico Martins, 642',
                'bairro' => 'Centro',
                'aptos' => 298,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 366,
                'local' => 'Escola Maria Pereira Brandão',
                'endereco' => 'Rua Vereador Mundico Martins, 642',
                'bairro' => 'Centro',
                'aptos' => 297,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 112,
                'local' => 'Escola Joaquim José Monteiro',
                'endereco' => 'Lagoa dos Monteiros',
                'bairro' => 'Zona Rural',
                'aptos' => 170,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 113,
                'local' => 'Escola Joaquim José Monteiro',
                'endereco' => 'Lagoa dos Monteiros',
                'bairro' => 'Zona Rural',
                'aptos' => 170,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 161,
                'local' => 'Escola Joaquim José Monteiro',
                'endereco' => 'Lagoa dos Monteiros',
                'bairro' => 'Zona Rural',
                'aptos' => 170,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 209,
                'local' => 'Escola Joaquim José Monteiro',
                'endereco' => 'Lagoa dos Monteiros',
                'bairro' => 'Zona Rural',
                'aptos' => 166,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 117,
                'local' => 'Escola Raimunda Elvira Brandão',
                'endereco' => 'Lagoa Salgada',
                'bairro' => 'Zona Rural',
                'aptos' => 246,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 250,
                'local' => 'Escola Raimunda Elvira Brandão',
                'endereco' => 'Lagoa Salgada',
                'bairro' => 'Zona Rural',
                'aptos' => 254,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 383,
                'local' => 'Escola Raimunda Elvira Brandão',
                'endereco' => 'Lagoa Salgada',
                'bairro' => 'Zona Rural',
                'aptos' => 249,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 319,
                'local' => 'Escola Antônio Gregório do Nascimento',
                'endereco' => 'Belém',
                'bairro' => 'Zona Rural',
                'aptos' => 296,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 401,
                'local' => 'Escola Antônio Gregório do Nascimento',
                'endereco' => 'Belém',
                'bairro' => 'Zona Rural',
                'aptos' => 214,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 114,
                'local' => 'Escola Macário José de Farias',
                'endereco' => 'Pitombeiras',
                'bairro' => 'Zona Rural',
                'aptos' => 215,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 165,
                'local' => 'Escola Macário José de Farias',
                'endereco' => 'Pitombeiras',
                'bairro' => 'Zona Rural',
                'aptos' => 216,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 191,
                'local' => 'Escola Macário José de Farias',
                'endereco' => 'Pitombeiras',
                'bairro' => 'Zona Rural',
                'aptos' => 213,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 266,
                'local' => 'Escola Macário José de Farias',
                'endereco' => 'Pitombeiras',
                'bairro' => 'Zona Rural',
                'aptos' => 214,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 208,
                'local' => 'Escola Renato Gonçalves Louzada',
                'endereco' => 'Formosa',
                'bairro' => 'Preá',
                'aptos' => 312,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 233,
                'local' => 'Escola Pedro Marques da Cunha',
                'endereco' => 'Solidão',
                'bairro' => 'Zona Rural',
                'aptos' => 201,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 393,
                'local' => 'Escola Pedro Marques da Cunha',
                'endereco' => 'Solidão',
                'bairro' => 'Zona Rural',
                'aptos' => 127,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 239,
                'local' => 'Escola Filomeno Freitas Vasconcelos',
                'endereco' => 'Avenida Tenente Albano, SN',
                'bairro' => 'Tucuns',
                'aptos' => 329,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 273,
                'local' => 'Escola Filomeno Freitas Vasconcelos',
                'endereco' => 'Avenida Tenente Albano, SN',
                'bairro' => 'Tucuns',
                'aptos' => 324,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 321,
                'local' => 'Escola Filomeno Freitas Vasconcelos',
                'endereco' => 'Avenida Tenente Albano, SN',
                'bairro' => 'Tucuns',
                'aptos' => 334,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 370,
                'local' => 'Escola Filomeno Freitas Vasconcelos',
                'endereco' => 'Avenida Tenente Albano, SN',
                'bairro' => 'Tucuns',
                'aptos' => 337,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 434,
                'local' => 'Escola Filomeno Freitas Vasconcelos',
                'endereco' => 'Avenida Tenente Albano, SN',
                'bairro' => 'Tucuns',
                'aptos' => 152,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 264,
                'local' => 'Escola Valdemar de Paulo Ribeiro',
                'endereco' => 'Canafístula',
                'bairro' => 'Zona Rural',
                'aptos' => 266,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 360,
                'local' => 'Escola Valdemar de Paulo Ribeiro',
                'endereco' => 'Canafístula',
                'bairro' => 'Zona Rural',
                'aptos' => 209,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 260,
                'local' => 'Escola Santa Cecília',
                'endereco' => 'Aroeira',
                'bairro' => 'Zona Rural',
                'aptos' => 324,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 346,
                'local' => 'Escola Santa Cecília',
                'endereco' => 'Aroeira',
                'bairro' => 'Zona Rural',
                'aptos' => 322,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 308,
                'local' => 'Escola Bernardino José de Vasconcelos',
                'endereco' => 'Lagoa Velha',
                'bairro' => 'Zona Rural',
                'aptos' => 267,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 397,
                'local' => 'Escola Bernardino José de Vasconcelos',
                'endereco' => 'Lagoa Velha',
                'bairro' => 'Zona Rural',
                'aptos' => 232,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 198,
                'local' => 'Escola Raimundo Luiz da Silveira',
                'endereco' => 'Córrego da Poeira',
                'bairro' => 'Zona Rural',
                'aptos' => 204,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 389,
                'local' => 'Escola Raimundo Luiz da Silveira',
                'endereco' => 'Córrego da Poeira',
                'bairro' => 'Zona Rural',
                'aptos' => 135,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 175,
                'local' => 'Escola Filomena Martins dos Santos',
                'endereco' => 'Córrego da Poeira',
                'bairro' => 'Zona Rural',
                'aptos' => 176,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 193,
                'local' => 'Escola Filomena Martins dos Santos',
                'endereco' => 'Córrego da Poeira',
                'bairro' => 'Zona Rural',
                'aptos' => 166,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 197,
                'local' => 'Escola Filomena Martins dos Santos',
                'endereco' => 'Córrego da Poeira',
                'bairro' => 'Zona Rural',
                'aptos' => 167,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 300,
                'local' => 'Escola Filomena Martins dos Santos',
                'endereco' => 'Córrego da Poeira',
                'bairro' => 'Zona Rural',
                'aptos' => 177,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 317,
                'local' => 'Escola Filomena Martins dos Santos',
                'endereco' => 'Córrego da Poeira',
                'bairro' => 'Zona Rural',
                'aptos' => 170,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 354,
                'local' => 'Escola Filomena Martins dos Santos',
                'endereco' => 'Córrego da Poeira',
                'bairro' => 'Zona Rural',
                'aptos' => 166,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 421,
                'local' => 'Escola Filomena Martins dos Santos',
                'endereco' => 'Córrego da Poeira',
                'bairro' => 'Zona Rural',
                'aptos' => 171,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 262,
                'local' => 'Escola Constância de Sousa Muniz',
                'endereco' => 'Rua Manoel Ismael da Silveira, SN',
                'bairro' => 'São João',
                'aptos' => 282,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 281,
                'local' => 'Escola Constância de Sousa Muniz',
                'endereco' => 'Rua Manoel Ismael da Silveira, SN',
                'bairro' => 'São João',
                'aptos' => 275,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 311,
                'local' => 'Escola Constância de Sousa Muniz',
                'endereco' => 'Rua Manoel Ismael da Silveira, SN',
                'bairro' => 'São João',
                'aptos' => 278,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 385,
                'local' => 'Escola Constância de Sousa Muniz',
                'endereco' => 'Rua Manoel Ismael da Silveira, SN',
                'bairro' => 'São João',
                'aptos' => 286,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 398,
                'local' => 'Escola Constância de Sousa Muniz',
                'endereco' => 'Rua Manoel Ismael da Silveira, SN',
                'bairro' => 'São João',
                'aptos' => 270,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 422,
                'local' => 'Escola Constância de Sousa Muniz',
                'endereco' => 'Rua Manoel Ismael da Silveira, SN',
                'bairro' => 'São João',
                'aptos' => 124,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 325,
                'local' => 'Escola Raimunda Silveira de Sousa Carneiro',
                'endereco' => 'Preá',
                'bairro' => 'Preá',
                'aptos' => 345,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 361,
                'local' => 'Escola Raimunda Silveira de Sousa Carneiro',
                'endereco' => 'Preá',
                'bairro' => 'Preá',
                'aptos' => 345,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 404,
                'local' => 'Escola Raimunda Silveira de Sousa Carneiro',
                'endereco' => 'Preá',
                'bairro' => 'Preá',
                'aptos' => 342,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 415,
                'local' => 'Escola Raimunda Silveira de Sousa Carneiro',
                'endereco' => 'Preá',
                'bairro' => 'Preá',
                'aptos' => 344,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 419,
                'local' => 'Escola São Paulo',
                'endereco' => 'Cavalo Bravo',
                'bairro' => 'Zona Rural',
                'aptos' => 255,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 196,
                'local' => 'Escola Francisco Benedito de Farias',
                'endereco' => 'Poço Doce',
                'bairro' => 'Zona Rural',
                'aptos' => 242,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 219,
                'local' => 'Escola Francisco Benedito de Farias',
                'endereco' => 'Poço Doce',
                'bairro' => 'Zona Rural',
                'aptos' => 257,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 259,
                'local' => 'Escola Francisco Benedito de Farias',
                'endereco' => 'Poço Doce',
                'bairro' => 'Zona Rural',
                'aptos' => 254,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 387,
                'local' => 'Escola Francisco Benedito de Farias',
                'endereco' => 'Poço Doce',
                'bairro' => 'Zona Rural',
                'aptos' => 243,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'secao' => 391,
                'local' => 'Escola Francisco Benedito de Farias',
                'endereco' => 'Poço Doce',
                'bairro' => 'Zona Rural',
                'aptos' => 255,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
